# Generated by Django 5.0.1 on 2024-02-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listings_listing_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Not specified', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='creation_date',
            field=models.CharField(default='Unavailable', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.ManyToManyField(related_name='listings', to='auctions.listing'),
        ),
    ]
