# Generated by Django 5.0.1 on 2024-02-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_category_listing_creation_date_user_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
