# Generated by Django 5.0.2 on 2024-03-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_bids_bid'),
    ]

    operations = [

    ]
