# Generated by Django 5.0.2 on 2024-03-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_year'),
    ]

    operations = [

    ]
