# Generated by Django 5.0.2 on 2024-03-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_year'),
    ]

    operations = [

    ]
