# Generated by Django 5.0.2 on 2024-03-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
