# Generated by Django 5.0.2 on 2024-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='preview_description',
            field=models.CharField(default='Coming soon', max_length=110),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
